### ISSUE TITLE
Build Tree Bug

### ISSUE THREAD

**Issue by Yagth** [iCog-Labs-Dev/metta-moses-reduction#16]
@EyobAshenaki The build tree function defined in the [tree-ds.metta](https://github.com/iCog-Labs-Dev/metta-moses-reduction/blob/main/utilities/tree-ds.metta) wrongly classifies literals as a not node type.

**Comment by EyobAshenaki** [comment]
Yes. I have caught that myself. I have fixed it and pushed the changes in `feature/tree-helper-functions` branch. It hasn't been merged with main yet but you can pull from there.

**Comment by Yagth** [comment]
Cool.
